# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres:9-alpine"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
